# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20171029_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Site'),
        ),
        migrations.AlterField(
            model_name='product',
            name='client_id',
            field=models.CharField(default=uuid.UUID('b42ba2d0-6177-4f3a-be24-48d32d94cd81'), max_length=128, unique=True),
        ),
    ]
