# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 23:45
from __future__ import unicode_literals

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('title', models.CharField(max_length=128)),
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('image_link', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('catalog_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_link', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_link', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('online', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('product_id', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField()),
                ('client_id', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('BGN', 'Leva')], max_length=5)),
                ('image_link', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('online', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Site'),
        ),
    ]
