# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalogs',
            new_name='Catalog',
        ),
        migrations.AlterField(
            model_name='product',
            name='client_id',
            field=models.CharField(default=uuid.UUID('6febead8-6129-49bb-aebc-d8781110b939'), max_length=128, unique=True),
        ),
    ]
