# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20171119_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='site',
        ),
    ]
