# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20171028_1316'),
    ]

    operations = [
    ]
