# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 10:39
from __future__ import unicode_literals

from django.db import migrations


def populate_query_field_asset(apps, schema):
    Asset = apps.get_model('API', 'Asset')
    for asset in Asset.objects.all():
        asset.query_field = '{}-{}'.format(asset.asset_id, asset.title)
        asset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_asset_query_field'),
    ]

    operations = [
        migrations.RunPython(populate_query_field_asset),
    ]
