# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20171029_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Site'),
        ),
        migrations.AlterField(
            model_name='product',
            name='client_id',
            field=models.CharField(default=uuid.UUID('68ad363d-54fb-498b-887b-6f25a4901389'), max_length=128, unique=True),
        ),
    ]
