# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20171029_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='client_id',
            field=models.CharField(default=uuid.UUID('c2af2825-b9f3-414b-8c36-69950fd29037'), max_length=128, unique=True),
        ),
    ]
