# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20171125_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='query_field',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
