# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20171125_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='link',
        ),
        migrations.AddField(
            model_name='catalog',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
