# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 00:21
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import server.API.models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20171213_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='image_link',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[server.API.models.ValidateFileType('jpg', 'jpeg', 'png', 'bmp', 'gif')]),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image_link',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[server.API.models.ValidateFileType('jpg', 'jpeg', 'png', 'bmp', 'gif')]),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[server.API.models.ValidateFileType('pdf')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_link',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[server.API.models.ValidateFileType('jpg', 'jpeg', 'png', 'bmp', 'gif')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[server.API.models.ValidateFileType('jpg', 'jpeg', 'png', 'bmp', 'gif')]),
        ),
    ]
