# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20171216_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='client_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
