# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20171226_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='config_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
