# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20171226_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
