# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='items',
        ),
        migrations.AddField(
            model_name='site',
            name='items',
            field=models.ManyToManyField(to='API.Item'),
        ),
    ]
