# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_auto_20171226_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
