# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_auto_20171229_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pdf',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
