export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_CATEGORY_PRODUCTS = 'GET_CATEGORY_PRODUCTS'

export const GET_ASSETS = 'GET_ASSETS'

export const GET_CATEGORIES = 'GET_CATEGORIES'

export const SET_LANGUAGE = 'SET_LANGUAGE'
