# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def add_foreign_keys(apps, schema_editor):
        Asset = apps.get_model('API', 'Asset')
        Site = apps.get_model('API', 'Site')
        site = Site()
        site.save()
        for asset in Asset.objects.all():
            asset.site = Site.objects.get(id=1)
            asset.save()

    dependencies = [
        ('API', '0004_auto_20171029_1649'),
    ]

    operations = [
        migrations.RunPython(add_foreign_keys),
    ]
